type BookMutationResponse implements MutationResponse {
  code: String!
  success: Boolean!
  message: String!
  book: Book
}

type Mutation {
  addBook(isbn: Int!, title: String!, authorName: String!): Book
  updateBook(id: ID!, isbn: Int, title: String, authorId: ID): Book!
  deleteBook(id: ID!): Boolean!
}
